### PR TITLE
7.10.3

### PR DESCRIPTION
**Pull request by ChristopherBiscardi**
ping @psftw

### CODE REVIEW

**Comment by psftw** [comment]
I won't be able to test for a few days, but looks good on the surface.

**Comment by psftw** [comment]
Basic smoke testing complete.  Stack appears to be shaping up nicely, but there is an issue with the image as-is:

```
# stack build
Compiler version mismatched, found ghc-7.10.3 (x86_64), but expected minor version match with ghc-7.10.2 (x86_64) (based on resolver setting in /yesod-minimal/stack.yaml).
Try running "stack setup" to install the correct GHC into /root/.stack/programs/x86_64-linux/
```

By adding a line to the config (https://www.fpcomplete.com/blog/2015/12/stack-with-ghc-7-10-3), we can get around this message.  

With the current Haskell image, we are already taking responsible for bundling GHC + some tightly integrated libraries.  Stack would be one more thing to track.  In addition, Stack appears to effectively bring Stackage with it (?), and the workaround above to get LTS-3.20 working against GHC 7.10.3 is at least questionable.  If we had adopted Stack previously, we would still be in this situation, pending upstream adoption of 7.10.3 (https://github.com/fpco/stackage/issues/1029).

Overall, I really want to ship Stack with the Haskell image, but I'm a little hesitant due to the workaround and my lack of experience with it.

**Comment by ChristopherBiscardi** [comment]
The way I view stack is as a specific tool, like cabal and thus both should be easily usable in an image like this.

It's unfortunate that the error message stack gives in this situation is less than ideal (ie: there's no reason to run `stack setup`) and this will clearly lead to people running `stack setup`.

When considering the community momentum and the improvements to the build that stack can bring, It does seem worth including the tool by default.

For the compiler version mismatch, it's simple fix but if we ship the "global" fix I am concerned about what happens if there's a 7.10.4. Will we get a compiler version mismatch in the other direction? Will we have to do the same for 8.0, which is coming down the pipeline as well.

Another potential option is to pin the compiler: http://docs.haskellstack.org/en/stable/yaml_configuration.html#compiler

```
compiler: 7.10.3
compiler-check: match-exact
```

**Comment by ChristopherBiscardi** [comment]
also notable is LTS-4 which was released today: http://www.stackage.org/lts-4.0

**Comment by psftw** [comment]
Having finally rebuilt the image, put it through some testing, and played with stack more, I'm happy.  Ping me on the docs update when ready.

**Pull request merged**
