### PR TITLE
Added GHC 8.8

### PR DESCRIPTION
**Pull request by GrahamCampbell**
GHc 8.8.1, Stack 2.1.3, Cabal 3.0.0.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmmm, I am struggling to build on my machine due to:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   621    0   621    0     0   2061      0 --:--:-- --:--:-- --:--:--  2056
100 13.8M  100 13.8M    0     0  4767k      0  0:00:02  0:00:02 --:--:-- 7671k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   625    0   625    0     0   1010      0 --:--:-- --:--:-- --:--:--  1009
100   488  100   488    0     0    477      0  0:00:01  0:00:01 --:--:--   477
gpg: keybox '/tmp/tmp.XahG8aosUa/pubring.kbx' created
gpg: key 575159689BEFB442: 5 signatures not checked due to missing keys
gpg: /tmp/tmp.XahG8aosUa/trustdb.gpg: trustdb created
gpg: key 575159689BEFB442: public key "FPComplete <dev@fpcomplete.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1
gpg: Signature made Sun Jul 14 15:33:46 2019 UTC
gpg:                using RSA key 2C6A674E85EE3FB896AFC9B965101FF31C5C154D
gpg: Can't check signature: No public key
```

**Comment by psftw** [comment]
With stack 2.x the signatures come from a pool of keys instead of the single FPComplete key, as described in https://docs.haskellstack.org/en/stable/SIGNING_KEY/ . I've had success with adding the release signer's key explicitly and validating the relationship. Feel free to update your PR and I'll merge it after some additional testing.

```
-    gpg --batch --verify stack.tar.gz.asc stack.tar.gz && \
+    gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys 2C6A674E85EE3FB896AFC9B965101FF31C5C154D && \
+    gpg --batch --trusted-key 0x575159689BEFB442 --verify stack.tar.gz.asc stack.tar.gz && \
```

**Comment by GrahamCampbell** [comment]
Was able to build successfully on my machine now.

**Comment by GrahamCampbell** [comment]
If I change the base image to `debian:buster`, I am also able to build this. NB it uses GCC 8.3, rather than 6.3.

**Comment by GrahamCampbell** [comment]
Please let me know if I should update the PR with `debian:buster`.

**Comment by psftw** [comment]
Thank you :tada:
I did notice that some libraries are not building happily in 8.8.1 yet, even a few key ones like `cabal-install`. Most are working fine and this is expected as part of a GHC upgrade cycle.

**Comment by psftw** [comment]
I'm not opposed to a `buster` variant, but don't want to move the image to `buster` by default just yet.

**Pull request merged**
