### PR TITLE
add bash in docker image workflow

### PR DESCRIPTION
**Pull request by gregwebs**

### CODE REVIEW

**Comment by ChristopherBiscardi** [comment]
I haven't gone over this in more depth, but two quick things:

* It looks like the code is misaligned with the other code examples (indentation)
* Do we actually need the LANG environment variables? (I thought we had fixed that in the base image)

**Comment by gregwebs** [comment]
I removed the LANG stuff: I have that from when I went off of other images, so it may work.

For markdown there are 2 ways to get monospace: backticks or indentation. There shouldn't be a need to do both. But feel free to make any styling changes you want.

**Comment by psftw** [comment]
This can lead to confusing issues with UID/GIDs, so I can't recommend it without calling those out (and the details are not in my brain atm).  In addition, `haskell ALL=(ALL) NOPASSWD: ALL` basically negates the purpose of not using root (reduce privileges) except to appease scripts that check the user.  Once we have user namespaces in Docker, I think it will make sense to take another look at all official images and provide more guidance to users on how to approach these things.

**Comment by ChristopherBiscardi** [comment]
Closing due to inactivity

**Pull request closed without merging**
