### PR TITLE
8.2.1 upgrade

### PR DESCRIPTION
**Pull request by ajscholl**
Based on the 8.0 Dockerfile.

### CODE REVIEW

**Comment by phaazon** [comment]
Any news about that?

**Comment by siddhanathan** [comment]
Addresses issue #60. When can we expect to see this merged in?

**Comment by phaazon** [comment]
At work I just wrap that image in local. We’d like to use the Docker Store image instead of a local one of ours. So… yeah, can we move towards merging that? :)

**Comment by psftw** [comment]
Thank you @ajscholl :+1:

**Pull request merged**
