### PR TITLE
various cleanup, and version bump alex/happy

### PR DESCRIPTION
**Pull request by psftw**

### CODE REVIEW

**Comment by ChristopherBiscardi** [comment]
LGTM, merging

**Comment by md5** [comment]
Would it make sense to have something like this to make updates more predictable?

```Dockerfile
ENV \
    GHC_VERSION=7.10.1 \
    CABAL_INSTALL_VERSION=1.22 \
    ALEX_VERSION=3.1.4 \
    HAPPY_VERSION=1.19.5
```

This way someone can't accidentally miss updating the `PATH` variable or other places the version number is used.

**Comment by psftw** [comment]
@md5 absolutely.  I want to be able to do something like run a script to detect when there are updates in the upstream PPA and then generate Dockerfiles based on it.  This update was overdue and involved moving to a new install method, so getting it pushed out ASAP was higher priority than solving the update overhead properly.  I opened #22 along those lines.

**Comment by md5** [comment]
:+1:

**Pull request merged**
